#!/usr/bin/env python3
"""Generate sms_gate/web_assets.h from the www/ UI sources.

Each file is gzip-compressed (deterministic, mtime=0) and emitted as a PROGMEM
byte array. The output is included exactly once, by sms_gate/web_api.cpp.
"""

from __future__ import annotations

import gzip
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WWW_DIR = ROOT / "www"
OUT_PATH = ROOT / "sms_gate" / "web_assets.h"

# (file name, HTTP route, content type, array identifier)
ASSETS = [
    ("style.css", "/style.css", "text/css; charset=utf-8", "kStyleCss"),
    ("wifi.html", "/wifi", "text/html; charset=utf-8", "kWifiHtml"),
    ("admin.html", "/admin", "text/html; charset=utf-8", "kAdminHtml"),
    ("email.html", "/email", "text/html; charset=utf-8", "kEmailHtml"),
    ("time.html", "/time", "text/html; charset=utf-8", "kTimeHtml"),
    ("modem.html", "/modem", "text/html; charset=utf-8", "kModemHtml"),
    ("zte.html", "/zte", "text/html; charset=utf-8", "kZteHtml"),
    ("gps.html", "/gps", "text/html; charset=utf-8", "kGpsHtml"),
    ("sms.html", "/sms", "text/html; charset=utf-8", "kSmsHtml"),
    ("js/main.js", "/js/main.js", "text/javascript; charset=utf-8", "kMainJs"),
    ("js/wifi.js", "/js/wifi.js", "text/javascript; charset=utf-8", "kWifiJs"),
    ("js/admin.js", "/js/admin.js", "text/javascript; charset=utf-8", "kAdminJs"),
    ("js/email.js", "/js/email.js", "text/javascript; charset=utf-8", "kEmailJs"),
    ("js/time.js", "/js/time.js", "text/javascript; charset=utf-8", "kTimeJs"),
    ("js/modem.js", "/js/modem.js", "text/javascript; charset=utf-8", "kModemJs"),
    ("js/zte.js", "/js/zte.js", "text/javascript; charset=utf-8", "kZteJs"),
    ("js/gps.js", "/js/gps.js", "text/javascript; charset=utf-8", "kGpsJs"),
    ("js/sms.js", "/js/sms.js", "text/javascript; charset=utf-8", "kSmsJs"),
]


def gzip_bytes(data: bytes) -> bytes:
    return gzip.compress(data, compresslevel=9, mtime=0)


def c_array(ident: str, data: bytes) -> str:
    lines = [f"const unsigned char {ident}[] PROGMEM = {{"]
    for offset in range(0, len(data), 16):
        chunk = ", ".join(f"0x{byte:02x}" for byte in data[offset : offset + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parts = [
        "// Generated by tools/gen_assets.py from www/. Do not edit.",
        "// Include exactly once: sms_gate/web_api.cpp.",
        "#pragma once",
        "",
        "#include <pgmspace.h>",
        "",
        "namespace web_assets {",
        "",
        "struct Asset {",
        "  const char* path;",
        "  const char* contentType;",
        "  const unsigned char* data;",
        "  const unsigned int size;",
        "  const char* etag;",
        "};",
        "",
    ]
    total_raw = 0
    total_packed = 0
    entries = []
    for file_name, route, content_type, ident in ASSETS:
        raw = (WWW_DIR / file_name).read_bytes()
        packed = gzip_bytes(raw)
        total_raw += len(raw)
        total_packed += len(packed)
        etag = f'"{zlib.crc32(packed) & 0xFFFFFFFF:08x}"'
        entries.append((route, content_type, ident, etag))
        parts.append(c_array(ident, packed))
        parts.append("")
        print(
            f"asset={file_name} raw={len(raw)} gzip={len(packed)} route={route}"
        )
    parts.append("const Asset kAssets[] = {")
    for route, content_type, ident, etag in entries:
        parts.append(
            f'    {{"{route}", "{content_type}", {ident}, sizeof {ident}, {etag}}},'
        )
    parts.append("};")
    parts.append("")
    parts.append("}  // namespace web_assets")
    parts.append("")
    OUT_PATH.write_text("\n".join(parts), encoding="utf-8")
    print(
        f"event=assets_generated out={OUT_PATH.relative_to(ROOT)} "
        f"assets={len(ASSETS)} raw_bytes={total_raw} gzip_bytes={total_packed}"
    )


if __name__ == "__main__":
    main()
